server:
  port: 8001

spring:
  application:
    name: authentication-service
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/chessleader
    username: "root"
    password: "dinhwe2612"
    driver-class-name: com.mysql.cj.jdbc.Driver

security:
  jwt:
    token:
      secret-key: dinhwe2612
      expire-length: 604800000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka/
